services:
  - type: web
    name: todoism-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask initdb && flask translate compile && flask run --host=0.0.0.0 --port 5001
