services:
  - type: web
    name: todoism-app
    runtime: python  
    buildCommand: |
      pip install -r requirements.txt
      flask initdb
      flask translate compile
    startCommand: flask run --host=0.0.0.0 --port $PORT
